version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: electron
        update-types: [version-update:semver-major]
      - dependency-name: electron-builder
        update-types: [version-update:semver-major]
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
