import type { WorkflowPack } from '../types.js';

export const buildScreenPack: WorkflowPack = {
  id: 'build-screen',
  name: 'Build Screen',
  description: 'Create a new screen or page layout from scratch, section by section.',
  triggers: [
    { keywords: ['crea schermata', 'create screen', 'create page'], intentCategory: 'build', confidence: 0.9 },
    {
      keywords: [
        'costruisci pagina',
        'build screen',
        'build page',
        'design page',
        'make landing page',
        'trasforma in UI',
      ],
      intentCategory: 'build',
      confidence: 0.9,
    },
    { keywords: ['crea una', 'build a', 'create a'], intentCategory: 'build', confidence: 0.6 },
  ],
  capabilities: ['ds-read', 'component-reuse', 'ds-proactive', 'visual-validation'],
  supportedModes: ['bootstrap', 'socratic', 'execution', 'review'],
  phases: [
    {
      id: 'status',
      name: 'Connection Check',
      description: 'Verify Figma connection and current page state.',
      mandatorySteps: ['Call figma_status to verify connection'],
      exitCriteria: ['Connection confirmed', 'Current page identified'],
      antiPatterns: [],
      userCheckpoint: false,
      validationType: 'none',
    },
    {
      id: 'discovery',
      name: 'Discovery',
      description: 'Inspect existing page content, search for reusable components and tokens.',
      mandatorySteps: [
        'Call figma_design_system to check DS status',
        'Call figma_search_components for relevant components',
        'Call figma_get_file_data to inspect page structure',
      ],
      exitCriteria: ['DS status known', 'Available components cataloged', 'Page structure understood'],
      antiPatterns: ['Skipping discovery and jumping to creation', 'Not checking library components'],
      userCheckpoint: false,
      validationType: 'structural',
    },
    {
      id: 'plan',
      name: 'Plan',
      description: 'Propose screen structure and get user approval before building.',
      mandatorySteps: [
        'Propose section breakdown (header, hero, content, footer etc.)',
        'Identify which components to reuse vs create',
        'Present plan to user',
      ],
      exitCriteria: ['User approves structure plan'],
      antiPatterns: ['Building without user approval', 'Proposing structure without knowing available components'],
      userCheckpoint: true,
      validationType: 'none',
    },
    {
      id: 'build',
      name: 'Build',
      description: 'Build one section at a time: create wrapper, build content, validate.',
      mandatorySteps: [
        'Create section wrapper frame with auto-layout',
        'Build section content (instantiate components or create from scratch)',
        'Validate each section with figma_get_file_data after building',
      ],
      exitCriteria: ['All planned sections built', 'Each section structurally validated'],
      antiPatterns: [
        'Building sections as top-level children and reparenting later',
        'Creating more than one section per tool call',
        'Hardcoding hex colors when DS variables exist',
        'Creating components from scratch when similar ones exist',
        'Using figma_execute when dedicated tools cover the operation',
      ],
      userCheckpoint: false,
      validationType: 'both',
    },
    {
      id: 'validate',
      name: 'Final Validation',
      description: 'Take final screenshot and fix any visual issues.',
      mandatorySteps: [
        'Call figma_screenshot for full visual verification',
        'Fix any visible issues (max 3 screenshot/fix loops)',
      ],
      exitCriteria: ['Screenshot shows correct result', 'No visible defects'],
      antiPatterns: ['Skipping final screenshot', 'Taking more than 3 screenshots without fixing anything'],
      userCheckpoint: false,
      validationType: 'visual',
    },
  ],
  references: [
    { id: 'design-system-discovery', title: 'Design System Discovery', content: '', loadCondition: 'on-demand' },
    { id: 'visual-validation', title: 'Visual Validation', content: '', loadCondition: 'on-demand' },
    { id: 'component-reuse', title: 'Component Reuse', content: '', loadCondition: 'on-demand' },
  ],
  validationPolicy: {
    afterMutation: [{ type: 'structural', description: 'Check node tree after each creation' }],
    afterMilestone: [{ type: 'visual', description: 'Screenshot after each section complete' }],
    maxScreenshotLoops: 3,
    requiredChecks: ['discovery-before-create', 'no-duplicate-creation'],
  },
  requiresStateLedger: false,
  requiresUserCheckpoints: true,
};
