import type { WorkflowPack } from '../types.js';

export const updateScreenPack: WorkflowPack = {
  id: 'update-screen',
  name: 'Update Screen',
  description: 'Apply targeted, minimal mutations to an existing screen or frame.',
  triggers: [
    {
      keywords: [
        'aggiorna schermata',
        'modifica frame',
        'cambia header',
        'cambia colore',
        'cambia layout',
        'aggiorna design',
      ],
      intentCategory: 'update',
      confidence: 0.9,
    },
    {
      keywords: [
        'update design',
        'fix layout',
        'change design',
        'update layout',
        'update screen',
        'update frame',
        'update header',
        'change color',
        'change layout',
        'change header',
        'update the header',
        'update the footer',
        'update the button',
        'change the header',
        'change the footer',
        'change the button',
        'change the color',
        'change the layout',
        'update the design',
        'change the design',
        'the header design',
        'the button color',
        'button color',
        'header design',
      ],
      intentCategory: 'update',
      confidence: 0.75,
    },
  ],
  capabilities: ['ds-read', 'targeted-diff', 'ds-lint', 'visual-validation'],
  supportedModes: ['socratic', 'execution', 'review'],
  phases: [
    {
      id: 'read',
      name: 'Read',
      description: 'Read current screen structure and identify target nodes.',
      mandatorySteps: [
        'Call figma_get_file_data to load current structure',
        'Call figma_get_selection if user has selected nodes',
        'Identify exact node IDs for targeted mutations',
      ],
      exitCriteria: ['Target nodes identified', 'Current state understood'],
      antiPatterns: [
        'Assuming node IDs without reading current structure',
        'Proceeding without identifying target nodes',
      ],
      userCheckpoint: false,
      validationType: 'structural',
    },
    {
      id: 'diff',
      name: 'Diff',
      description: 'Identify the minimal set of changes needed to achieve the desired result.',
      mandatorySteps: [
        'Compare current state with desired outcome',
        'List the specific mutations required (no more, no less)',
        'Present diff plan to user for confirmation',
      ],
      exitCriteria: ['Mutation list confirmed by user', 'Scope explicitly bounded'],
      antiPatterns: [
        'Planning full screen recreation instead of minimal mutations',
        'Including nodes outside target scope without user confirmation',
        'Ignoring component properties in favor of direct node edits',
      ],
      userCheckpoint: true,
      validationType: 'none',
    },
    {
      id: 'mutate',
      name: 'Mutate',
      description: 'Apply only the planned mutations, verifying each one.',
      mandatorySteps: [
        'Apply mutations one at a time in planned order',
        'Verify each mutation with figma_get_file_data',
        'Stop immediately if an unplanned change is detected',
      ],
      exitCriteria: ['All planned mutations applied', 'No unintended side effects'],
      antiPatterns: [
        'Recreating the entire screen instead of targeted mutations',
        'Modifying nodes outside the target scope without user confirmation',
        'Ignoring component properties — use figma_set_instance_properties, not direct edits',
      ],
      userCheckpoint: false,
      validationType: 'structural',
    },
    {
      id: 'validate',
      name: 'Validate',
      description: 'Visual and lint validation to confirm no regressions.',
      mandatorySteps: [
        'Call figma_lint to check for DS violations introduced',
        'Call figma_screenshot for visual regression check',
        'Fix any defects introduced by the mutations (max 3 loops)',
      ],
      exitCriteria: ['Lint passes', 'No visual regressions visible', 'Screenshot confirms desired result'],
      antiPatterns: ['Skipping post-update validation', 'Accepting lint warnings without reviewing them'],
      userCheckpoint: false,
      validationType: 'both',
    },
  ],
  references: [
    { id: 'targeted-diff', title: 'Targeted Diff', content: '', loadCondition: 'on-demand' },
    { id: 'visual-validation', title: 'Visual Validation', content: '', loadCondition: 'on-demand' },
  ],
  validationPolicy: {
    afterMutation: [{ type: 'structural', description: 'Verify only targeted nodes changed' }],
    afterMilestone: [{ type: 'visual', description: 'Screenshot check for regressions' }],
    maxScreenshotLoops: 3,
    requiredChecks: ['discovery-before-create', 'no-duplicate-creation'],
  },
  requiresStateLedger: false,
  requiresUserCheckpoints: true,
};
